
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.aguare.appgraphic.Back;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int C_BRACE = 23;
  public static final int TYPE_BARS = 5;
  public static final int MULTIPLY = 20;
  public static final int COLONS = 29;
  public static final int SEMICOLON = 28;
  public static final int ID_GRAPHIC = 7;
  public static final int START_GRAPHIC = 4;
  public static final int DECIMAL = 3;
  public static final int SUMA = 18;
  public static final int O_PARENT = 26;
  public static final int C_PARENT = 27;
  public static final int STRING = 30;
  public static final int C_SBRACKET = 25;
  public static final int TYPE = 13;
  public static final int COMMA = 31;
  public static final int TYPE_ATTRIBUTE = 14;
  public static final int EOF = 0;
  public static final int TOTAL = 15;
  public static final int DIVIDE = 21;
  public static final int VALUES = 11;
  public static final int RUN = 17;
  public static final int EXTRA = 16;
  public static final int error = 1;
  public static final int TYPE_PIE = 6;
  public static final int O_BRACE = 22;
  public static final int AXIS_Y = 9;
  public static final int INTEGER = 2;
  public static final int AXIS_X = 8;
  public static final int TAGS = 10;
  public static final int O_SBRACKET = 24;
  public static final int JOIN = 12;
  public static final int RESTA = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "DECIMAL",
  "START_GRAPHIC",
  "TYPE_BARS",
  "TYPE_PIE",
  "ID_GRAPHIC",
  "AXIS_X",
  "AXIS_Y",
  "TAGS",
  "VALUES",
  "JOIN",
  "TYPE",
  "TYPE_ATTRIBUTE",
  "TOTAL",
  "EXTRA",
  "RUN",
  "SUMA",
  "RESTA",
  "MULTIPLY",
  "DIVIDE",
  "O_BRACE",
  "C_BRACE",
  "O_SBRACKET",
  "C_SBRACKET",
  "O_PARENT",
  "C_PARENT",
  "SEMICOLON",
  "COLONS",
  "STRING",
  "COMMA"
  };
}

